### ISSUE TITLE
Can't locate Archive/Extract.pm

### ISSUE THREAD

**Issue by coringao** [coringao/runescape#3]
When running the executable file, it warns that 'Archive/Extract.pm' was not found.

`$ ./src/runescape
`
> `Can't locate Archive/Extract.pm in @INC (you may need to install the Archive::Extract module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/games/runescape/rsu/rsu-query line 16.`
> `BEGIN failed--compilation aborted at /usr/share/games/runescape/rsu/rsu-query line 16.`

**Fixed commenting on line 16 of file 'rsu/rsu-query'.**
```
# Include the module for extracting archives
# use Archive::Extract;
```

**Comment by HikariKnight** [comment]
i forgot to give you this dependency sorry

libarchive-extract-perl

hence the error, my bad

**Comment by coringao** [comment]
Thanks, added in README.md and uncommented.
